-- 코드를 입력하세요
WITH FILTERED_BOOK_SALES AS (
    SELECT BOOK_ID, SALES_DATE, SALES
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
)

SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(B.PRICE * F.SALES) AS TOTAL_SALES
FROM 
    FILTERED_BOOK_SALES F
JOIN BOOK B ON B.BOOK_ID = F.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY
    A.AUTHOR_ID, B.CATEGORY
ORDER BY 
    A.AUTHOR_ID, B.CATEGORY DESC;
    