-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM((P.PRICE * O.SALES_AMOUNT)) AS SALES
FROM OFFLINE_SALE O
JOIN PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;