-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
        (SELECT N.SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
        FROM ONLINE_SALE AS N
        WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE <= '2022-03-31'
    UNION
        SELECT F.SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT
        FROM OFFLINE_SALE AS F
        WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE <= '2022-03-31') AS T
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
