-- 코드를 입력하세요
WITH USERS_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'
),
ONLINE_SALE_FILTERED AS (
    SELECT 
        USER_ID, 
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    GROUP BY USER_ID, YEAR, MONTH
)

SELECT
    YEAR,
    MONTH,
    COUNT(O.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USERS_2021), 
        1
    ) AS PURCHASED_RATIO
FROM ONLINE_SALE_FILTERED O
JOIN USERS_2021 U
ON O.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH
HAVING PURCHASED_USERS > 0
ORDER BY YEAR ASC, MONTH ASC;
