-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_CTE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT e.ID, gc.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GENERATION_CTE gc ON e.PARENT_ID = gc.ID
),

LEAF_ONLY AS (
    SELECT g.ID, g.GENERATION
    FROM GENERATION_CTE g
    LEFT JOIN ECOLI_DATA c ON g.ID = c.PARENT_ID
    WHERE c.ID IS NULL
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM LEAF_ONLY
GROUP BY GENERATION
ORDER BY GENERATION;
