-- 코드를 입력하세요
WITH TRUCK_RENTAL AS (
  SELECT
    H.HISTORY_ID,
    H.CAR_ID,
    C.DAILY_FEE,
    DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENT_DAYS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
  WHERE C.CAR_TYPE = '트럭'
),
DISCOUNT_MATCHED AS (
  SELECT
    T.HISTORY_ID,
    T.DAILY_FEE,
    T.RENT_DAYS,
    P.DISCOUNT_RATE,
    ROW_NUMBER() OVER (
      PARTITION BY T.HISTORY_ID
      ORDER BY CAST(REGEXP_REPLACE(P.DURATION_TYPE, '[^0-9]', '') AS UNSIGNED) DESC
    ) AS RN
  FROM TRUCK_RENTAL T
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON P.CAR_TYPE = '트럭'
   AND T.RENT_DAYS >= CAST(REGEXP_REPLACE(P.DURATION_TYPE, '[^0-9]', '') AS UNSIGNED)
)
SELECT
  HISTORY_ID,
  ROUND(
    CASE
      WHEN DISCOUNT_RATE IS NOT NULL THEN DAILY_FEE * RENT_DAYS * (1 - (CAST(REPLACE(DISCOUNT_RATE, '%', '') AS DECIMAL) / 100))
      ELSE DAILY_FEE * RENT_DAYS
    END
  ) AS FEE
FROM DISCOUNT_MATCHED
WHERE RN = 1
ORDER BY FEE DESC, HISTORY_ID DESC;
