-- 코드를 입력하세요
WITH JULY_SUM AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
    FROM JULY
    GROUP BY FLAVOR
),
FIRST_HALF_SUM AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
    FROM FIRST_HALF
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
FROM FIRST_HALF_SUM F
JOIN JULY_SUM J
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 0, 3;