-- 코드를 입력하세요
WITH RECURSIVE HOUR_CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM HOUR_CTE
    WHERE HOUR < 23
)

SELECT 
    HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM HOUR_CTE AS H
LEFT OUTER JOIN ANIMAL_OUTS AS A
ON HOUR(A.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR ASC;