-- 코드를 작성해주세요
WITH FE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY LIKE '%Front%'
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
JOIN FE
ON (SKILL_CODE & FE.CODE) > 0
ORDER BY ID ASC;