-- 코드를 입력하세요
WITH USER_INFO AS (
    SELECT USER_ID, NICKNAME
    FROM USED_GOODS_USER
), 
BOARD AS (
    SELECT WRITER_ID, PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
)

SELECT I.USER_ID, I.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USER_INFO I
JOIN BOARD B ON I.USER_ID = B.WRITER_ID
GROUP BY I.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;
