-- 코드를 작성해주세요
WITH MAX_CTE AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM (FISH_INFO F
        JOIN FISH_NAME_INFO N
        ON F.FISH_TYPE = N.FISH_TYPE
      ) 
      JOIN MAX_CTE
      ON F.FISH_TYPE = MAX_CTE.FISH_TYPE AND F.LENGTH = MAX_CTE.LENGTH
ORDER BY F.ID ASC;
    