-- 코드를 작성해주세요
WITH EMP_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
),
MAX_SCORE AS (
    SELECT MAX(SCORE) AS MAX_S
    FROM EMP_SCORE
)

SELECT DISTINCT M.MAX_S AS SCORE, H.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES H
JOIN EMP_SCORE S ON H.EMP_NO = S.EMP_NO
JOIN MAX_SCORE M ON S.SCORE = M.MAX_S;

