-- 코드를 입력하세요
WITH MAX_CTE AS (
    SELECT 
        CATEGORY, 
        MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING
        CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT 
    F.CATEGORY, 
    F.PRICE, 
    F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN MAX_CTE M ON F.CATEGORY = M.CATEGORY
WHERE F.PRICE = M.MAX_PRICE
ORDER BY F.PRICE DESC;
