-- 코드를 작성해주세요
WITH DEV_SKILLS AS (
  SELECT 
    D.ID,
    D.EMAIL,
    S.CATEGORY,
    S.NAME AS SKILL_NAME
  FROM DEVELOPERS D
  JOIN SKILLCODES S
    ON D.SKILL_CODE & S.CODE > 0
),
GRADE_CTE AS (
  SELECT 
    ID,
    EMAIL,
    MAX(CASE WHEN CATEGORY = 'Front End' THEN 1 ELSE 0 END) AS HAS_FE,
    MAX(CASE WHEN SKILL_NAME = 'Python' THEN 1 ELSE 0 END) AS HAS_PYTHON,
    MAX(CASE WHEN SKILL_NAME = 'C#' THEN 1 ELSE 0 END) AS HAS_CSHARP
  FROM DEV_SKILLS
  GROUP BY ID, EMAIL
)
SELECT 
  CASE
    WHEN HAS_FE = 1 AND HAS_PYTHON = 1 THEN 'A'
    WHEN HAS_CSHARP = 1 THEN 'B'
    WHEN HAS_FE = 1 THEN 'C'
    ELSE NULL
  END AS GRADE,
  ID,
  EMAIL
FROM GRADE_CTE
WHERE 
(HAS_FE = 1 AND HAS_PYTHON = 1) OR
  HAS_CSHARP = 1 OR
  HAS_FE = 1
 ORDER BY GRADE, ID;